### ISSUE TITLE
Crash (Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout)

### ISSUE THREAD

**Issue by adiga-maf** [InflationX/Calligraphy#35] opened 2019-06-27 14:58 UTC
I am facing an issue on Android Q (API 29), getting the following exception when open the app:

```
java.lang.RuntimeException: Unable to start activity 
     ComponentInfo{com.example.app/com.example.app.MainActivity}: 
     android.view.InflateException: Binary XML file line #17 
     in com.example.app:layout/abc_screen_simple: Binary XML file line #17 
     in com.example.app:layout/abc_screen_simple: 
         Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
```
I don't have neither `abc_screen_simple` layout nor `FitWindowsLinearLayout`.
I tried many articles related even in old library versions but no luck. I would appreciate if you help with this.

**Comment by lucas-ferreira-machado** [comment] 2019-07-03 21:27
Please update to the new **viewpump** version 2.0.3 in your build.gradle. 
It worked for me.

**implementation** 'io.github.inflationx:viewpump:**2.0.3**'

**Comment by HardyInfotech** [comment] 2020-07-24 12:26
How to solve it... Please help me ...

Binary XML file line #17 in packga_name:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout

**Comment by AlejandroHCruz** [comment] 2020-08-19 16:04
Hi, I'm experiencing the same issue. Here's the complete stack trace, in case it helps:

@lucas-ferreira-machado do you have any further advice? I'm using `implementation 'io.github.inflationx:viewpump:2.0.3'` & calligraphy v3.1.1

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.debug/com.myapp.MainActivity}: android.view.InflateException: Binary XML file line #17 in com.myapp.debug:layout/abc_screen_simple: Binary XML file line #17 in com.myapp.debug:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #17 in com.myapp.debug:layout/abc_screen_simple: Binary XML file line #17 in com.myapp.debug:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: android.view.InflateException: Binary XML file line #17 in com.myapp.debug:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
        at io.github.inflationx.viewpump.ReflectionUtils.getValue(ReflectionUtils.java:25)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.createCustomViewInternal(ViewPumpLayoutInflater.java:196)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.access$000(ViewPumpLayoutInflater.java:14)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(ViewPumpLayoutInflater.java:405)
        at io.github.inflationx.viewpump.FallbackViewCreationInterceptor.intercept(FallbackViewCreationInterceptor.java:11)
        at io.github.inflationx.viewpump.InterceptorChain.proceed(InterceptorChain.java:37)
        at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
        at io.github.inflationx.viewpump.InterceptorChain.proceed(InterceptorChain.java:37)
        at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.java:49)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(ViewPumpLayoutInflater.java:385)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.inflate(ViewPumpLayoutInflater.java:55)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:920)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
```

**Comment by AlejandroHCruz** [comment] 2020-08-19 16:17
@HardyInfotech I can confirm this has been fixed after using:

-    `implementation 'io.github.inflationx:calligraphy3:3.1.1'`
-   `  implementation 'io.github.inflationx:viewpump:2.0.3'`

If you need more help, consider commenting [here](https://stackoverflow.com/questions/56524914/crash-on-android-10-inflateexception-in-layout-abc-screen-simple-line-17/57232072#57232072)

And also feel free of closing #53 as it's a duplicate of this issue right here.

**Comment by gijsdewit** [comment] 2020-09-03 11:42
In addition to AlejandroHCruz's answer on updating to the latest versions, I used `androidx.appcompat:appcompat:1.1.0` instead of version `1.2.0`, which seems to break it again. Not sure yet why, but for now using `1.1.0` solved the issue.

**Comment by chrisjenx** [comment] 2021-02-19 15:35
Thank you @AlejandroHCruz !

**Closed as completed** 2021-02-19 15:36 UTC
