### ISSUE TITLE
crash on android Q

### ISSUE THREAD

**Issue by ghost1372** [InflationX/Calligraphy#34] opened 2019-06-10 13:27 UTC
hi calligraphy crash on android Q please check it
this part of code make crash
```
 @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(ViewPumpContextWrapper.wrap(newBase));
    }
```

**Comment by jbarr21** [comment] 2019-06-10 16:20
Dupe of #33

**Closed as completed by jbarr21** 2019-06-10 16:20 UTC

**Comment by ghost1372** [comment] 2019-06-10 16:27
@jbarr21 so, is there any way to fix this?
